apiVersion: apps/v1
kind: Deployment
metadata:
  name: newmovie
  labels:
    app: newmovie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newmovie
  template:
    metadata:
      labels:
        app: newmovie
    spec:
      containers:
        - name: newmovie
          image: 566584275819.dkr.ecr.ap-northeast-2.amazonaws.com/kmbaek:newMovie
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
