apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend
  labels:
    app: recommend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:
      containers:
        - name: recommend
          image: 566584275819.dkr.ecr.ap-northeast-2.amazonaws.com/kmbaek:recommend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
