apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: 566584275819.dkr.ecr.ap-northeast-2.amazonaws.com/kmbaek:bff
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
