apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: 566584275819.dkr.ecr.ap-northeast-2.amazonaws.com/kmbaek:logger
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
