apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  labels:
    app: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: 566584275819.dkr.ecr.ap-northeast-2.amazonaws.com/kmbaek:movie
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
